
void tables_orcc(int N, double *y, 
	    double a1, double *x1, double a2, double *x2, 
	    double a3, double *x3) {

/*@ begin PerfTuning (
 def build {
   arg build_command = 'cc -O0';
 } 
 def performance_counter {
   arg repetitions = 10;
 }
 def performance_params {  
   param UF[] = range(1,33);
 }
 def input_params {
   param N[] = [100000000];
 }
 def input_vars {
   decl dynamic double x1[N] = random;
   decl dynamic double x2[N] = random;
   decl dynamic double x3[N] = random;
   decl dynamic double y[N] = 0;
   decl double a1 = 0.5;
   decl double a2 = 1.0;
   decl double a3 = 1.5;
 }
 def search {
   arg algorithm = 'Exhaustive';
 }
) @*/
/**-- (Generated by Orio) 
Best performance cost: 
  [0.662383, 0.663889, 0.664019, 0.663793, 0.664048, 0.663838, 0.664347, 0.663656, 0.663826, 0.663843] 
Tuned for specific problem sizes: 
  N = 100000000 
Best performance parameters: 
  UF = 3 
--**/


  int n=N;
  register int i;

/*@ begin Loop ( 
  transform Unroll(ufactor=UF) 
  for (i=0; i<=n-1; i++)
    y[i]=y[i]+a1*x1[i]+a2*x2[i]+a3*x3[i];
) @*/
{
  int i;
  for (i=0; i<=n-3; i=i+3) {
    y[i]=y[i]+a1*x1[i]+a2*x2[i]+a3*x3[i];
    y[(i+1)]=y[(i+1)]+a1*x1[(i+1)]+a2*x2[(i+1)]+a3*x3[(i+1)];
    y[(i+2)]=y[(i+2)]+a1*x1[(i+2)]+a2*x2[(i+2)]+a3*x3[(i+2)];
  }
  for (i=n-((n-(0))%3); i<=n-1; i=i+1) 
    y[i]=y[i]+a1*x1[i]+a2*x2[i]+a3*x3[i];
}
/*@ end @*/
/*@ end @*/

}
